name       : flask-httpauth
version    : 4.5.0
release    : 5
source     :
    - https://github.com/miguelgrinberg/Flask-HTTPAuth/archive/refs/tags/v4.5.0.tar.gz : dc57d8808ba910ec85a18b82f1f07c52d37f417c0e97ef4395dc9b093a9bdecc
homepage   : https://github.com/miguelgrinberg/Flask-HTTPAuth
license    : MIT
component  : programming.python
summary    : Basic and Digest HTTP authentication for Flask routes
description: |
    Simple flask extension that provides Basic, Digest and Token HTTP authentication for Flask routes.
builddeps  :
    - flask
    - python-pytest-cov
    #- python-tox
rundeps    :
    - flask
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # require python-asgiref
#    python3_test tox -e py39
