name       : flask-httpauth
version    : 4.7.0
release    : 6
source     :
    - https://github.com/miguelgrinberg/Flask-HTTPAuth/archive/refs/tags/v4.7.0.tar.gz : 1260ce0bffe242ed9120d83d272aeb05dded76ffa709a0df60416d936427cca1
homepage   : https://github.com/miguelgrinberg/Flask-HTTPAuth
license    : MIT
component  : programming.python
summary    : Basic and Digest HTTP authentication for Flask routes
description: |
    Simple flask extension that provides Basic, Digest and Token HTTP authentication for Flask routes.
builddeps  :
    - flask
    - python-asgiref    # check
    - python-pytest-cov # check
rundeps    :
    - flask
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
