name       : flask-httpauth
version    : 3.3.0
release    : 2
source     :
    - https://github.com/miguelgrinberg/Flask-HTTPAuth/archive/v3.3.0.tar.gz : d0ee4c08eaff879a43be1b6a7f9efcbb38ceffbcda84da30979fcc8b9d037eaf
license    : MIT
component  : programming.python
summary    : Simple flask extension that provides Basic, Digest and Token HTTP authentication for Flask routes.
description: |
    Simple flask extension that provides Basic, Digest and Token HTTP authentication for Flask routes.
builddeps  :
    - flask
rundeps    :
    - flask
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
